import { NextResponse } from 'next/server'

/**
 * This route is no longer called during practice sessions.
 * Questions are now pre-generated by `npm run db:generate-questions` and stored in the DB.
 * To regenerate questions with AI, run that script manually.
 */
export async function POST() {
  return NextResponse.json(
    { error: 'Runtime AI generation is disabled. Run npm run db:generate-questions to regenerate the question bank.' },
    { status: 410 }
  )
}
